# --- DATOS DEL SITIO ---
title: "Sinapsis"
name: "Sinapsis"
description: "Conectando tecnología y sociedad."
url: "" 
baseurl: "" 
locale: "es-ES"
favicon: "/assets/images/favicon.ico"
logo: "/assets/images/logo.png"

# --- TEMA VISUAL ---
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

# --- PLUGINS NECESARIOS ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# --- CONFIGURACIÓN DE ESTILO ---
# Esto activa la barra lateral con tu foto en todas las páginas
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      share: false

# --- PAGINACIÓN ---
paginate: 10
paginate_path: /page:num/

# --- DATOS DEL AUTOR (Barra Lateral) ---
author:
  name: "Jesús Báez"
  bio: "Analista de tecnología y sociedad."
  location: "Zaragoza - España"
  #avatar: "/assets/images/jesus-baez.jpg"
  links:
    - label: "@jsbaez"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/jsbaez"
    - label: "Jesús Báez"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jsbaez/"

include: ["_pages"]